/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessCustomersRouteImport } from './routes/business.customers'
import { Route as BusinessProgramRouteImport } from './routes/business.program'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessCustomersRoute = BusinessCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessProgramRoute = BusinessProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => BusinessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRouteWithChildren
  '/business/customers': typeof BusinessCustomersRoute
  '/business/program': typeof BusinessProgramRoute
  '/business/': typeof BusinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/program': typeof BusinessProgramRoute
  '/business': typeof BusinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRouteWithChildren
  '/business/customers': typeof BusinessCustomersRoute
  '/business/program': typeof BusinessProgramRoute
  '/business/': typeof BusinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/business'
    | '/business/customers'
    | '/business/program'
    | '/business/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/business/customers' | '/business/program' | '/business'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/business'
    | '/business/customers'
    | '/business/program'
    | '/business/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BusinessRoute: typeof BusinessRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/customers': {
      id: '/business/customers'
      path: '/customers'
      fullPath: '/business/customers'
      preLoaderRoute: typeof BusinessCustomersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/program': {
      id: '/business/program'
      path: '/program'
      fullPath: '/business/program'
      preLoaderRoute: typeof BusinessProgramRouteImport
      parentRoute: typeof BusinessRoute
    }
  }
}

interface BusinessRouteChildren {
  BusinessCustomersRoute: typeof BusinessCustomersRoute
  BusinessProgramRoute: typeof BusinessProgramRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessCustomersRoute: BusinessCustomersRoute,
  BusinessProgramRoute: BusinessProgramRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BusinessRoute: BusinessRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
