/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as BusinessAnalyticsRouteImport } from './routes/business.analytics'
import { Route as BusinessCustomersRouteImport } from './routes/business.customers'
import { Route as BusinessProgramRouteImport } from './routes/business.program'
import { Route as BusinessQrRouteImport } from './routes/business.qr'
import { Route as BusinessRewardsRouteImport } from './routes/business.rewards'
import { Route as BusinessSettingsRouteImport } from './routes/business.settings'
import { Route as BusinessTransactionsRouteImport } from './routes/business.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessAnalyticsRoute = BusinessAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessCustomersRoute = BusinessCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessProgramRoute = BusinessProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessQrRoute = BusinessQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessRewardsRoute = BusinessRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSettingsRoute = BusinessSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessTransactionsRoute = BusinessTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => BusinessRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRouteWithChildren
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/program': typeof BusinessProgramRoute
  '/business/qr': typeof BusinessQrRoute
  '/business/rewards': typeof BusinessRewardsRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/transactions': typeof BusinessTransactionsRoute
  '/business/': typeof BusinessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/program': typeof BusinessProgramRoute
  '/business/qr': typeof BusinessQrRoute
  '/business/rewards': typeof BusinessRewardsRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/transactions': typeof BusinessTransactionsRoute
  '/business': typeof BusinessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/business': typeof BusinessRouteWithChildren
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/program': typeof BusinessProgramRoute
  '/business/qr': typeof BusinessQrRoute
  '/business/rewards': typeof BusinessRewardsRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/transactions': typeof BusinessTransactionsRoute
  '/business/': typeof BusinessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/business'
    | '/business/analytics'
    | '/business/customers'
    | '/business/program'
    | '/business/qr'
    | '/business/rewards'
    | '/business/settings'
    | '/business/transactions'
    | '/business/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/business/analytics'
    | '/business/customers'
    | '/business/program'
    | '/business/qr'
    | '/business/rewards'
    | '/business/settings'
    | '/business/transactions'
    | '/business'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/business'
    | '/business/analytics'
    | '/business/customers'
    | '/business/program'
    | '/business/qr'
    | '/business/rewards'
    | '/business/settings'
    | '/business/transactions'
    | '/business/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BusinessRoute: typeof BusinessRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/analytics': {
      id: '/business/analytics'
      path: '/analytics'
      fullPath: '/business/analytics'
      preLoaderRoute: typeof BusinessAnalyticsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/customers': {
      id: '/business/customers'
      path: '/customers'
      fullPath: '/business/customers'
      preLoaderRoute: typeof BusinessCustomersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/program': {
      id: '/business/program'
      path: '/program'
      fullPath: '/business/program'
      preLoaderRoute: typeof BusinessProgramRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/qr': {
      id: '/business/qr'
      path: '/qr'
      fullPath: '/business/qr'
      preLoaderRoute: typeof BusinessQrRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/rewards': {
      id: '/business/rewards'
      path: '/rewards'
      fullPath: '/business/rewards'
      preLoaderRoute: typeof BusinessRewardsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/settings': {
      id: '/business/settings'
      path: '/settings'
      fullPath: '/business/settings'
      preLoaderRoute: typeof BusinessSettingsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/transactions': {
      id: '/business/transactions'
      path: '/transactions'
      fullPath: '/business/transactions'
      preLoaderRoute: typeof BusinessTransactionsRouteImport
      parentRoute: typeof BusinessRoute
    }
  }
}

interface BusinessRouteChildren {
  BusinessAnalyticsRoute: typeof BusinessAnalyticsRoute
  BusinessCustomersRoute: typeof BusinessCustomersRoute
  BusinessProgramRoute: typeof BusinessProgramRoute
  BusinessQrRoute: typeof BusinessQrRoute
  BusinessRewardsRoute: typeof BusinessRewardsRoute
  BusinessSettingsRoute: typeof BusinessSettingsRoute
  BusinessTransactionsRoute: typeof BusinessTransactionsRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessAnalyticsRoute: BusinessAnalyticsRoute,
  BusinessCustomersRoute: BusinessCustomersRoute,
  BusinessProgramRoute: BusinessProgramRoute,
  BusinessQrRoute: BusinessQrRoute,
  BusinessRewardsRoute: BusinessRewardsRoute,
  BusinessSettingsRoute: BusinessSettingsRoute,
  BusinessTransactionsRoute: BusinessTransactionsRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BusinessRoute: BusinessRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
